import localFont from 'next/font/local'

// Self-hosted subsets generated by scripts/subset-fonts.mjs (rerun it if new characters appear in copy).

// Serif, now only for the "Siegel" wordmark and the invoice letterhead: small, so not preloaded.
export const instrumentSerif = localFont({
  src: '../app/fonts/instrument-serif.woff2',
  weight: '400',
  variable: '--font-instrument',
  display: 'swap',
  preload: false,
  adjustFontFallback: 'Times New Roman',
  fallback: ['Georgia', 'serif'],
})

export const geistSans = localFont({
  src: '../app/fonts/geist-sans.woff2',
  variable: '--font-geist-sans',
  weight: '300 500',
  display: 'swap',
})

// Mono is only used for small labels and numbers: not preloaded, so it never competes
// with the headline and body fonts for first paint.
export const geistMono = localFont({
  src: '../app/fonts/geist-mono.woff2',
  variable: '--font-geist-mono',
  weight: '400',
  display: 'swap',
  preload: false,
  adjustFontFallback: false,
  fallback: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
})

export const fontVariables = `${instrumentSerif.variable} ${geistSans.variable} ${geistMono.variable}`
