import localFont from 'next/font/local'

// Self-hosted subsets generated by scripts/subset-fonts.mjs (rerun it if new characters appear in copy).

// Display serif: regular for headlines, italic for accent words.
export const instrumentSerif = localFont({
  src: [
    { path: '../app/fonts/instrument-serif.woff2', weight: '400', style: 'normal' },
    { path: '../app/fonts/instrument-serif-italic.woff2', weight: '400', style: 'italic' },
  ],
  variable: '--font-instrument',
  display: 'swap',
  adjustFontFallback: 'Times New Roman',
  fallback: ['Georgia', 'serif'],
})

// Hero headline only: Boska Medium (ITF, Fontshare), one upright style.
export const boska = localFont({
  src: '../app/fonts/boska-medium.woff2',
  variable: '--font-hero',
  weight: '500',
  display: 'swap',
  adjustFontFallback: 'Times New Roman',
  fallback: ['Georgia', 'serif'],
})

export const geistSans = localFont({
  src: '../app/fonts/geist-sans.woff2',
  variable: '--font-geist-sans',
  weight: '400 500',
  display: 'swap',
})

// Mono is only used for small labels and numbers: not preloaded, so it never competes
// with the headline and body fonts for first paint.
export const geistMono = localFont({
  src: '../app/fonts/geist-mono.woff2',
  variable: '--font-geist-mono',
  weight: '400',
  display: 'swap',
  preload: false,
  adjustFontFallback: false,
  fallback: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
})

export const fontVariables = `${instrumentSerif.variable} ${boska.variable} ${geistSans.variable} ${geistMono.variable}`
