import localFont from 'next/font/local'

// Self-hosted subsets generated by scripts/subset-fonts.mjs (rerun it if new characters appear in copy).

// Headline serif, weight 400, with its optical-size axis kept for the display cut at large sizes.
export const newsreader = localFont({
  src: '../app/fonts/newsreader.woff2',
  variable: '--font-newsreader',
  weight: '400',
  display: 'swap',
  adjustFontFallback: 'Times New Roman',
  fallback: ['Georgia', 'serif'],
})

export const geistSans = localFont({
  src: '../app/fonts/geist-sans.woff2',
  variable: '--font-geist-sans',
  weight: '400 500',
  display: 'swap',
})

// Mono is only used for small labels and numbers: not preloaded, so it never competes
// with the headline and body fonts for first paint.
export const geistMono = localFont({
  src: '../app/fonts/geist-mono.woff2',
  variable: '--font-geist-mono',
  weight: '400',
  display: 'swap',
  preload: false,
  adjustFontFallback: false,
  fallback: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
})

export const fontVariables = `${newsreader.variable} ${geistSans.variable} ${geistMono.variable}`
